Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end
  
  config.vm.synced_folder "./scripts", "/opt/scripts"
  config.vm.network "private_network", ip: "192.168.56.14"
  config.vm.network "public_network", bridge: "eth0"
  
  config.vm.provision "shell", inline: <<-SHELL
    echo "Vagrant VM with ubuntu/jammy64 is ready!"
  SHELL
end
